### PR TITLE
Zsb/feature/extend chakra theme

### PR DESCRIPTION
**Pull request by zberwaldt**
There are a few of the components that need to be refined to closer match the spec from the Figma design. But what is in the branch should be usable in pages. If you want me to clean things up more, let me know, I'll be happy to do that.

### CODE REVIEW

**Review by PradhumnaPancholi — APPROVED** [review]
LGTM!

**Comment by zberwaldt** [comment]
Right, to develop first, yes?

**Review by PradhumnaPancholi — CHANGES_REQUESTED** [review]
Hey @zberwaldt, can you please create a merge request for develop rather than main.

**Comment by zberwaldt** [comment]
@PradhumnaPancholi my bad, updated the base.

**Comment by PradhumnaPancholi** [comment]
> @PradhumnaPancholi my bad, updated the base.

Thanks

**Review by PradhumnaPancholi — APPROVED** [review]

**Pull request merged**
